=== denisfadjob/Lenguajes_marcas/1. XML/gimnasio.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elemento raíz -->
    <xs:element name="gimnasio">

        <xs:complexType>
            <xs:sequence>

                <!-- Una o varias rutinas -->
                <xs:element name="rutina" maxOccurs="3">

                    <xs:complexType>
                        <xs:sequence>

                            <!-- Nombre de la rutina -->
                            <xs:element name="nombre" type="xs:string"/>

                            <!-- Nivel de la rutina -->
                            <xs:element name="nivel" type="xs:string"/>

                            <!-- Lista de ejercicios -->
                            <xs:element name="ejercicios">

                                <xs:complexType>
                                    <xs:sequence>

                                        <!-- Uno o varios ejercicios -->
                                        <xs:element name="ejercicio" maxOccurs="3">

                                            <xs:complexType>
                                                <xs:sequence>

                                                    <!-- Nombre del ejercicio -->
                                                    <xs:element name="nombre" type="xs:string"/>

                                                    <!-- Número de series -->
                                                    <xs:element name="series" type="xs:integer"/>

                                                    <!-- Número de repeticiones -->
                                                    <xs:element name="repeticiones" type="xs:integer"/>

                                                </xs:sequence>
                                            </xs:complexType>

                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>

                        <!-- Atributo obligatorio de la rutina -->
                        <xs:attribute name="id"
                                      type="xs:string"
                                      use="required"/>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>

=== denisfadjob/Lenguajes_marcas/1. XML/gimnasio.xml
<?xml version="1.0" encoding="UTF-8"?>

<gimnasio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="gimnasio.xsd">

    <rutina id="RUT001">
        <nombre>Rutina de fuerza</nombre>
        <nivel>Intermedio</nivel>

        <ejercicios>
            <ejercicio>
                <nombre>Press banca</nombre>
                <series>4</series>
                <repeticiones>10</repeticiones>
            </ejercicio>

            <ejercicio>
                <nombre>Sentadilla</nombre>
                <series>4</series>
                <repeticiones>8</repeticiones>
            </ejercicio>

            <ejercicio>
                <nombre>Remo con barra</nombre>
                <series>3</series>
                <repeticiones>10</repeticiones>
            </ejercicio>
        </ejercicios>

    </rutina>


    <rutina id="RUT002">
        <nombre>Rutina de iniciación</nombre>
        <nivel>Principiante</nivel>

        <ejercicios>
            <ejercicio>
                <nombre>Press militar</nombre>
                <series>3</series>
                <repeticiones>12</repeticiones>
            </ejercicio>

            <ejercicio>
                <nombre>Prensa de piernas</nombre>
                <series>3</series>
                <repeticiones>12</repeticiones>
            </ejercicio>

             <ejercicio>
                <nombre>Prensa de piernas</nombre>
                <series>3</series>
                <repeticiones>12</repeticiones>
            </ejercicio>

        </ejercicios>

    </rutina>

    <rutina id="RUT003">
        <nombre>Rutina de iniciación</nombre>
        <nivel>Principiante</nivel>

        <ejercicios>
            <ejercicio>
                <nombre>Press militar</nombre>
                <series>3</series>
                <repeticiones>12</repeticiones>
            </ejercicio>

            <ejercicio>
                <nombre>Prensa de piernas</nombre>
                <series>3</series>
                <repeticiones>12</repeticiones>
            </ejercicio>
        </ejercicios>

    </rutina>

</gimnasio>
